### ISSUE TITLE
svelte.config.cjs convert to ES Module?

### ISSUE THREAD

**Issue by ryanrussell** [FractalHQ/sveltekit-electron#5]
Hello,

npm run dev works fine for me, but I get an error on build. New to this stack, apologies in advance if this is something I missed.

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

$ node --version
v14.17.0

$ npm --version
7.13.0

$ npm run build

> sveltekit-electron@0.0.1 build
> cross-env NODE_ENV=production npm run build:svelte && npm run build:electron

> sveltekit-electron@0.0.1 build:svelte
> svelte-kit build

svelte.config.cjs should be renamed to svelte.config.js and converted to an ES module. See https://kit.svelte.dev/docs#configuration for an example
No "exports" main defined in /home/ryan/lab/sveltekit-electron/node_modules/@sveltejs/adapter-static/package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/ryan/lab/sveltekit-electron/node_modules/@sveltejs/adapter-static/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:479:7)
    at resolveExports (internal/modules/cjs/loader.js:437:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:477:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:872:27)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/ryan/lab/sveltekit-electron/svelte.config.cjs:2:16)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)

Thanks in advance for any suggestions.

**Comment by FractalHQ** [comment]
Hey @ryanrussell!  Sorry for the delay on this.  Ever figure this out?  The last I checked the build was working but I never got a chance to test it on Linux.  That issue looks familiar though- usually adding `"type": "module"` into `package.json` can fix that.  I'll take a look now.

**Comment by FractalHQ** [comment]
@ryanrussell Looks like there were a few changes to sveltekit internals.  Got everything up-to-date and tested the build- works great!  Let me know if this works out for you, and thanks for bringing up the issue!

**Comment by ryanrussell** [comment]
Thanks for responding and the OSS contribution. Works like a charm.
